In [1]:
import numpy as np, pandas as pd

df1 = pd.read_csv('CMAPSSData/train_FD001_w_label.csv')

In [2]:
df1.head()

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_15,s_16,s_17,s_18,s_19,s_20,s_21,max_cycle,RUL,label
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8.4195,0.03,392,2388,100.0,39.06,23.4190,192,191,0
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8.4318,0.03,392,2388,100.0,39.00,23.4236,192,190,0
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8.4178,0.03,390,2388,100.0,38.95,23.3442,192,189,0
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8.3682,0.03,392,2388,100.0,38.88,23.3739,192,188,0
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8.4294,0.03,393,2388,100.0,38.90,23.4044,192,187,0

In [13]:
df1.describe()

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_15,s_16,s_17,s_18,s_19,s_20,s_21,max_cycle,RUL,label
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,20631.00,20631.000000,20631.000000,20631.000000,2.063100e+04,...,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000,20631.000000,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,100.0,518.67,642.680934,1590.523119,1408.933782,1.462000e+01,...,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705,216.615724,107.807862,0.150259
std,29.227633,68.880990,0.002187,0.000293,0.0,0.00,0.500053,6.131150,9.000605,5.329200e-15,...,0.037505,3.469531e-18,1.548763,0.0,0.0,0.180746,0.108251,50.028600,68.880990,0.357334
min,1.000000,1.000000,-0.008700,-0.000600,100.0,518.67,641.210000,1571.040000,1382.250000,1.462000e+01,...,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200,128.000000,0.000000,0.000000
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,518.67,642.325000,1586.260000,1402.360000,1.462000e+01,...,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800,185.000000,51.000000,0.000000
50%,52.000000,104.000000,0.000000,0.000000,100.0,518.67,642.640000,1590.100000,1408.040000,1.462000e+01,...,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900,207.000000,103.000000,0.000000
75%,77.000000,156.000000,0.001500,0.000300,100.0,518.67,643.000000,1594.380000,1414.555000,1.462000e+01,...,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800,240.000000,155.000000,0.000000
max,100.000000,362.000000,0.008700,0.000600,100.0,518.67,644.530000,1616.910000,1441.490000,1.462000e+01,...,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400,362.000000,361.000000,1.000000

# Normalize before reshape into array

In [24]:
df_norm = df1.copy()

for column in df_norm.columns[2:-3]:
    df_norm[column] = (df_norm[column] - df_norm[column].mean()) / df_norm[column].std()

In [25]:
df_norm.head()

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_15,s_16,s_17,s_18,s_19,s_20,s_21,max_cycle,RUL,label
0,1,1,-0.315972,-1.372920,NaN,NaN,-1.721684,-0.134252,-0.925914,-0.999976,...,-0.603801,-0.999976,-0.781691,NaN,NaN,1.348460,1.194398,192,191,0
1,1,2,0.872701,-1.031695,NaN,NaN,-1.061754,0.211523,-0.643710,-0.999976,...,-0.275845,-0.999976,-0.781691,NaN,NaN,1.016503,1.236892,192,190,0
2,1,3,-1.961827,1.015652,NaN,NaN,-0.661797,-0.413156,-0.525940,-0.999976,...,-0.649128,-0.999976,-2.073044,NaN,NaN,0.739873,0.503411,192,189,0
3,1,4,0.324083,-0.008022,NaN,NaN,-0.661797,-1.261284,-0.784812,-0.999976,...,-1.971617,-0.999976,-0.781691,NaN,NaN,0.352590,0.777773,192,188,0
4,1,5,-0.864590,-0.690471,NaN,NaN,-0.621801,-1.251498,-0.301511,-0.999976,...,-0.339837,-0.999976,-0.136014,NaN,NaN,0.463242,1.059526,192,187,0

In [26]:
df_norm.isnull().sum()

unit_number        0
time_cycles        0
setting_1          0
setting_2          0
setting_3      20631
s_1            20631
s_2                0
s_3                0
s_4                0
s_5                0
s_6                0
s_7                0
s_8                0
s_9                0
s_10           20631
s_11               0
s_12               0
s_13               0
s_14               0
s_15               0
s_16               0
s_17               0
s_18           20631
s_19           20631
s_20               0
s_21               0
max_cycle          0
RUL                0
label              0
dtype: int64

In [27]:
samples = []
for unit in df_norm.unit_number.unique():
    engine = df_norm[(df_norm.unit_number == unit) & (df_norm.label == 0)].dropna(axis=1).drop(['unit_number', 'time_cycles', 'max_cycle', 'RUL', 'label'], axis=1).reset_index(drop=True).to_numpy()
    
    for i in range(len(engine) - 50 + 1):
        features = []
        for j in engine[i: i+50]:
            features.append(j)

        samples.append(np.array(features))

samples = np.array(samples)

# Reshape to something (N, 50, 24)

In [28]:
samples

array([[[-0.31597202, -1.37291993, -1.72168366, ..., -0.78169084,
          1.34846006,  1.1943981 ],
        [ 0.87270078, -1.03169535, -1.06175397, ..., -0.78169084,
          1.01650329,  1.23689198],
        [-1.96182667,  1.01565212, -0.66179659, ..., -2.07304398,
          0.73987265,  0.50341061],
        ...,
        [ 0.87270078,  0.33320296, -1.58169858, ..., -0.78169084,
          0.68454653,  0.69555687],
        [-0.63599931,  1.69810128, -0.90177102, ..., -0.78169084,
          1.34846006,  1.47892236],
        [-1.45892664, -0.34924619,  0.17811393, ..., -0.78169084,
          0.18661137,  1.11680057]],

       [[ 0.87270078, -1.03169535, -1.06175397, ..., -0.78169084,
          1.01650329,  1.23689198],
        [-1.96182667,  1.01565212, -0.66179659, ..., -2.07304398,
          0.73987265,  0.50341061],
        [ 0.32408256, -0.00802161, -0.66179659, ..., -0.78169084,
          0.35258976,  0.77777329],
        ...,
        [-0.63599931,  1.69810128, -0.90177102, ..., -0.78169084,
          1.34846006,  1.47892236],
        [-1.45892664, -0.34924619,  0.17811393, ..., -0.78169084,
          0.18661137,  1.11680057],
        [-0.45312658,  1.01565212,  0.25810541, ..., -0.13601427,
          0.68454653,  0.69648065]],

       [[-1.96182667,  1.01565212, -0.66179659, ..., -2.07304398,
          0.73987265,  0.50341061],
        [ 0.32408256, -0.00802161, -0.66179659, ..., -0.78169084,
          0.35258976,  0.77777329],
        [-0.86459024, -0.69047077, -0.62180085, ..., -0.13601427,
          0.46324201,  1.05952621],
        ...,
        [-1.45892664, -0.34924619,  0.17811393, ..., -0.78169084,
          0.18661137,  1.11680057],
        [-0.45312658,  1.01565212,  0.25810541, ..., -0.13601427,
          0.68454653,  0.69648065],
        [ 0.82698259, -0.34924619,  0.15811606, ..., -1.42736741,
          1.01650329,  0.45352649]],

       ...,

       [[ 0.82698259, -0.69047077, -0.94176676, ..., -0.13601427,
         -0.03469314, -0.38249447],
        [ 0.91841896, -1.03169535, -0.22184346, ...,  0.5096623 ,
         -0.25599765, -0.42498835],
        [ 0.18692801,  1.01565212, -0.04186263, ...,  0.5096623 ,
         -0.20067152,  0.48493501],
        ...,
        [ 0.46123712,  1.3568767 ,  1.09801592, ...,  1.15533887,
         -2.24773826, -2.16723755],
        [ 0.36980075, -0.69047077,  1.03802232, ...,  1.15533887,
         -0.58795442, -1.76539322],
        [ 0.82698259, -1.37291993,  1.77794348, ...,  1.80101545,
         -1.1412157 , -0.57464072]],

       [[ 0.91841896, -1.03169535, -0.22184346, ...,  0.5096623 ,
         -0.25599765, -0.42498835],
        [ 0.18692801,  1.01565212, -0.04186263, ...,  0.5096623 ,
         -0.20067152,  0.48493501],
        [ 0.04977345, -1.03169535,  0.27810328, ..., -0.13601427,
         -0.09001927, -0.46655845],
        ...,
        [ 0.36980075, -0.69047077,  1.03802232, ...,  1.15533887,
         -0.58795442, -1.76539322],
        [ 0.82698259, -1.37291993,  1.77794348, ...,  1.80101545,
         -1.1412157 , -0.57464072],
        [-1.23033571, -0.69047077,  0.57807132, ...,  1.15533887,
         -1.1412157 , -0.2513177 ]],

       [[ 0.18692801,  1.01565212, -0.04186263, ...,  0.5096623 ,
         -0.20067152,  0.48493501],
        [ 0.04977345, -1.03169535,  0.27810328, ..., -0.13601427,
         -0.09001927, -0.46655845],
        [-0.13309928, -0.00802161, -1.18174119, ...,  0.5096623 ,
          0.68454653,  0.05722484],
        ...,
        [ 0.82698259, -1.37291993,  1.77794348, ...,  1.80101545,
         -1.1412157 , -0.57464072],
        [-1.23033571, -0.69047077,  0.57807132, ...,  1.15533887,
         -1.1412157 , -0.2513177 ],
        [-0.86459024, -1.03169535,  0.33809689, ...,  1.15533887,
         -0.58795442, -0.67995165]]], shape=(12631, 50, 19))

In [29]:
np.save("FD001", samples)