In [1]:
import numpy as np, pandas as pd

df_train = pd.read_csv('csv/train_FD001.csv')
df_test = pd.read_csv('csv/test_FD001.csv')

# Normalize

In [2]:
def norm(df):
    for column in df.columns[2:-1]:
        df[column] = (df[column] - df[column].mean()) / df[column].std()
    return df.dropna(axis="columns").drop(["unit_number", "time_cycles", "Fault"], axis=1)

df_train_norm = norm(df_train).copy()
df_test_norm = norm(df_test).copy()

# Match sensor size

In [ ]:
if (len(df_train_norm.columns) < len(df_test_norm.columns)):
    df_test_norm = df_test_norm[df_train_norm.columns].copy()
else: print("we have a problem")

we have a problem

In [6]:
df_train_norm

,setting_1,setting_2,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_11,s_12,s_13,s_14,s_15,s_16,s_17,s_20,s_21
0,-0.339199,-1.370495,-1.708895,-0.416354,-1.054499,-0.999917,0.151128,1.204721,-0.723930,-0.757103,-0.548627,0.594862,-1.143290,-0.335591,-0.813301,-0.999917,-0.944264,1.384861,1.263537
1,0.854031,-1.029689,-1.178318,-0.136391,-0.836653,-0.999917,0.151128,0.667958,-0.948852,-0.819708,-0.491687,1.243337,-0.589523,-0.579948,-0.555005,-0.999917,-0.944264,1.122123,1.296973
2,-1.991363,1.015148,-0.856756,-0.642173,-0.745741,-0.999917,0.151128,1.116727,-0.499008,-0.557771,-1.118022,1.389767,-1.032537,-0.520315,-0.849001,-0.999917,-1.977375,0.903175,0.719844
3,0.303310,-0.007271,-0.856756,-1.328874,-0.945576,-0.999917,0.151128,1.283916,-0.161625,-0.659947,-1.516599,1.849975,-0.478769,-0.499752,-1.890585,-0.999917,-0.944264,0.596648,0.935722
4,-0.889920,-0.688883,-0.824600,-1.320951,-0.572494,-0.999917,0.151128,0.887943,-0.723930,-0.492509,-1.089552,1.149204,-0.921783,-0.500781,-0.605404,-0.999917,-0.427708,0.684227,1.157415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,-0.201518,-1.029689,0.976146,0.677086,1.349523,-0.999917,0.151128,-1.373499,0.738062,-0.186276,1.159559,-1.674800,1.514795,-0.370548,0.784775,-0.999917,1.638515,-1.111147,-1.974636
5996,-0.752240,-1.711301,1.056537,1.538104,1.774065,-0.999917,0.151128,-1.875064,1.187906,-0.198383,1.074150,-1.476074,1.071780,-0.408247,1.169069,-0.999917,0.605403,-1.943149,-0.623398
5997,0.165629,-0.007271,0.863600,1.268706,1.310929,-0.999917,0.151128,-1.804669,1.300367,-0.175054,1.216499,-1.130918,1.293288,-0.252311,2.233753,-0.999917,2.155070,-1.330095,-2.266835
5998,-0.522772,1.015148,0.558116,1.638468,1.169415,-0.999917,0.151128,-2.033453,1.412828,0.055875,2.070592,-1.486533,1.182534,-0.312629,1.694061,-0.999917,0.605403,-1.986939,-1.316826
5999,-1.486535,-1.711301,1.554958,0.994025,1.650562,-0.999917,0.151128,-1.936660,1.525289,-0.305580,1.529666,-1.873526,1.514795,-0.379802,0.952772,-0.999917,1.121959,-1.636622,-1.402595

In [7]:
df_test_norm

,setting_1,setting_2,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_11,s_12,s_13,s_14,s_15,s_16,s_17,s_20,s_21
0,1.024559,1.000251,1.180219,-0.605573,-0.978799,-0.999911,0.176276,0.284655,-0.580509,-0.620397,-1.079026,0.052809,-0.748240,-1.112405,-0.740019,-0.999911,-0.490646,-0.141456,0.488481
1,-1.222928,-1.053289,-1.852411,-0.013355,-1.355621,-0.999911,0.176276,1.549108,-1.060953,-0.311541,0.290713,0.757571,-0.265025,0.050721,-1.523268,-0.999911,0.260098,0.898971,0.685466
2,0.125564,0.315738,-0.116172,-0.296345,-0.556057,-0.999911,0.176276,0.564166,-0.420360,-0.126955,0.290713,0.453242,-0.748240,-0.736270,0.483610,-0.999911,0.260098,1.289132,0.957544
3,1.878604,-0.026519,-0.162472,-0.824844,0.130056,-0.999911,0.176276,0.510926,-0.740657,-0.975036,-0.713762,-0.491780,-0.426097,-0.504802,-1.164672,-0.999911,-1.241390,0.768918,0.490658
4,0.620012,-0.026519,-0.000423,-0.249493,-0.477721,-0.999911,0.176276,0.630716,-1.060953,-1.028813,-0.576788,0.741554,-0.748240,-0.782564,-0.806077,-0.999911,-1.992134,0.703891,0.918365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5635,2.193252,-0.026519,1.689516,2.048163,1.395583,-0.999911,0.176276,-0.367536,-0.900805,6.079952,1.158215,-1.596976,-1.231454,6.139977,1.345498,-0.999911,1.010842,-1.507017,-1.428039
5636,-0.503732,-0.368775,1.643216,1.343499,2.241068,-0.999911,0.176276,-0.620427,-0.420360,5.957136,0.747293,-1.020352,0.218189,5.939096,0.706946,-0.999911,1.761586,-2.027231,-0.560653
5637,-0.278983,-1.053289,2.152513,0.867475,0.184081,-0.999911,0.176276,-0.860007,0.540528,6.402615,0.610319,-0.812127,-0.587168,6.467339,0.886244,-0.999911,1.761586,-1.702098,-1.344239
5638,-1.717375,0.315738,1.735816,1.212311,1.877752,-0.999911,0.176276,-0.420776,-0.100064,6.550866,0.792951,-0.571867,0.057118,6.735180,1.332916,-0.999911,1.761586,-1.441991,-0.639012
5639,0.575062,1.000251,1.018170,2.454844,2.638149,-0.999911,0.176276,-1.605369,-0.260212,6.999978,1.660453,-0.988318,-0.426097,6.252404,1.936867,-0.999911,2.512330,-1.181884,-1.557549

# Convert to numpy

In [8]:
train_npy = df_train_norm.to_numpy()
test_npy = df_test_norm.to_numpy()

# Reshape to something (N, 30, len(sensor))

In [9]:
train_npy = train_npy.reshape(-1, 30, train_npy.shape[-1])
test_npy = test_npy.reshape(-1, 30, train_npy.shape[-1])

In [10]:
print(train_npy.shape, test_npy.shape)

(200, 30, 19) (188, 30, 19)

In [11]:
np.save("npy/train_FD001", train_npy)
np.save("npy/test_FD001", test_npy)