In [1]:
import numpy as np, pandas as pd

df = pd.read_csv('csv/test_FD001.csv')

In [2]:
df

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,Fault
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,0
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,0
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,0
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,0
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5635,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,1
5636,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,1
5637,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,1
5638,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,1
5639,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,1

# Normalize before reshape into array

In [3]:
df_norm = df.copy()

for column in df_norm.columns[2:-1]:
    df_norm[column] = (df_norm[column] - df_norm[column].mean()) / df_norm[column].std()

In [4]:
df_norm

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,Fault
0,1,1,1.024559,1.000251,NaN,NaN,1.180219,-0.605573,-0.978799,-0.999911,...,-0.748240,-1.112405,-0.740019,-0.999911,-0.490646,NaN,NaN,-0.141456,0.488481,0
1,1,2,-1.222928,-1.053289,NaN,NaN,-1.852411,-0.013355,-1.355621,-0.999911,...,-0.265025,0.050721,-1.523268,-0.999911,0.260098,NaN,NaN,0.898971,0.685466,0
2,1,3,0.125564,0.315738,NaN,NaN,-0.116172,-0.296345,-0.556057,-0.999911,...,-0.748240,-0.736270,0.483610,-0.999911,0.260098,NaN,NaN,1.289132,0.957544,0
3,1,4,1.878604,-0.026519,NaN,NaN,-0.162472,-0.824844,0.130056,-0.999911,...,-0.426097,-0.504802,-1.164672,-0.999911,-1.241390,NaN,NaN,0.768918,0.490658,0
4,1,5,0.620012,-0.026519,NaN,NaN,-0.000423,-0.249493,-0.477721,-0.999911,...,-0.748240,-0.782564,-0.806077,-0.999911,-1.992134,NaN,NaN,0.703891,0.918365,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5635,100,194,2.193252,-0.026519,NaN,NaN,1.689516,2.048163,1.395583,-0.999911,...,-1.231454,6.139977,1.345498,-0.999911,1.010842,NaN,NaN,-1.507017,-1.428039,1
5636,100,195,-0.503732,-0.368775,NaN,NaN,1.643216,1.343499,2.241068,-0.999911,...,0.218189,5.939096,0.706946,-0.999911,1.761586,NaN,NaN,-2.027231,-0.560653,1
5637,100,196,-0.278983,-1.053289,NaN,NaN,2.152513,0.867475,0.184081,-0.999911,...,-0.587168,6.467339,0.886244,-0.999911,1.761586,NaN,NaN,-1.702098,-1.344239,1
5638,100,197,-1.717375,0.315738,NaN,NaN,1.735816,1.212311,1.877752,-0.999911,...,0.057118,6.735180,1.332916,-0.999911,1.761586,NaN,NaN,-1.441991,-0.639012,1
5639,100,198,0.575062,1.000251,NaN,NaN,1.018170,2.454844,2.638149,-0.999911,...,-0.426097,6.252404,1.936867,-0.999911,2.512330,NaN,NaN,-1.181884,-1.557549,1

In [5]:
df_norm.isnull().sum()

unit_number       0
time_cycles       0
setting_1         0
setting_2         0
setting_3      5640
s_1            5640
s_2               0
s_3               0
s_4               0
s_5               0
s_6               0
s_7               0
s_8               0
s_9               0
s_10              0
s_11              0
s_12              0
s_13              0
s_14              0
s_15              0
s_16              0
s_17              0
s_18           5640
s_19           5640
s_20              0
s_21              0
Fault             0
dtype: int64

In [6]:
df_norm.dropna(axis="columns")

,unit_number,time_cycles,setting_1,setting_2,s_2,s_3,s_4,s_5,s_6,s_7,...,s_11,s_12,s_13,s_14,s_15,s_16,s_17,s_20,s_21,Fault
0,1,1,1.024559,1.000251,1.180219,-0.605573,-0.978799,-0.999911,0.176276,0.284655,...,-1.079026,0.052809,-0.748240,-1.112405,-0.740019,-0.999911,-0.490646,-0.141456,0.488481,0
1,1,2,-1.222928,-1.053289,-1.852411,-0.013355,-1.355621,-0.999911,0.176276,1.549108,...,0.290713,0.757571,-0.265025,0.050721,-1.523268,-0.999911,0.260098,0.898971,0.685466,0
2,1,3,0.125564,0.315738,-0.116172,-0.296345,-0.556057,-0.999911,0.176276,0.564166,...,0.290713,0.453242,-0.748240,-0.736270,0.483610,-0.999911,0.260098,1.289132,0.957544,0
3,1,4,1.878604,-0.026519,-0.162472,-0.824844,0.130056,-0.999911,0.176276,0.510926,...,-0.713762,-0.491780,-0.426097,-0.504802,-1.164672,-0.999911,-1.241390,0.768918,0.490658,0
4,1,5,0.620012,-0.026519,-0.000423,-0.249493,-0.477721,-0.999911,0.176276,0.630716,...,-0.576788,0.741554,-0.748240,-0.782564,-0.806077,-0.999911,-1.992134,0.703891,0.918365,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5635,100,194,2.193252,-0.026519,1.689516,2.048163,1.395583,-0.999911,0.176276,-0.367536,...,1.158215,-1.596976,-1.231454,6.139977,1.345498,-0.999911,1.010842,-1.507017,-1.428039,1
5636,100,195,-0.503732,-0.368775,1.643216,1.343499,2.241068,-0.999911,0.176276,-0.620427,...,0.747293,-1.020352,0.218189,5.939096,0.706946,-0.999911,1.761586,-2.027231,-0.560653,1
5637,100,196,-0.278983,-1.053289,2.152513,0.867475,0.184081,-0.999911,0.176276,-0.860007,...,0.610319,-0.812127,-0.587168,6.467339,0.886244,-0.999911,1.761586,-1.702098,-1.344239,1
5638,100,197,-1.717375,0.315738,1.735816,1.212311,1.877752,-0.999911,0.176276,-0.420776,...,0.792951,-0.571867,0.057118,6.735180,1.332916,-0.999911,1.761586,-1.441991,-0.639012,1
5639,100,198,0.575062,1.000251,1.018170,2.454844,2.638149,-0.999911,0.176276,-1.605369,...,1.660453,-0.988318,-0.426097,6.252404,1.936867,-0.999911,2.512330,-1.181884,-1.557549,1

In [7]:
# samples = []
# for unit in df_norm.unit_number.unique():
#     engine = df_norm[(df_norm.unit_number == unit) & (df_norm.Fault == 0)].dropna(axis=1).drop(['unit_number', 'time_cycles',  'Fault'], axis=1).reset_index(drop=True).to_numpy()
    
#     for i in range(len(engine) - 50 + 1):
#         features = []
#         for j in engine[i: i+50]:
#             features.append(j)

#         samples.append(np.array(features))

# samples = np.array(samples)

npy = df_norm.drop(columns=["unit_number", "time_cycles", "Fault"]).dropna(axis="columns").to_numpy()

# Reshape to something (N, 50, 24)

In [11]:
npy = npy.reshape(-1, 30, npy.shape[-1])

In [12]:
npy.shape

(188, 30, 20)

In [13]:
np.save("npy/test_FD001", npy)